targets:
  $default:
    builders:
      objectbox_generator:
        options:
          # Specify the location of your models
          output_dir: "lib/object_box/objectbox"
      freezed:
        options:
          # Ensure freezed generates mutable properties
          copy_with: true
          mutable: true