import 'dart:math';

class MessageGenerator {
  static final List<String> messages = [
    "Have a great day!",
    "Keep pushing forward!",
    "You're doing amazing!",
    "Believe in yourself!",
    "Success is on the horizon!",
    "Stay positive!",
    "You're stronger than you think!",
    "Never give up!",
    "Dream big, work hard!",
    "Great things take time!",
    "Your potential is endless!",
    "Stay focused and never quit!",
    "Every day is a new opportunity!",
    "The best is yet to come!",
    "Embrace the journey!",
    "Challenges are opportunities!",
    "You're on the right track!",
    "Stay determined!",
    "One step at a time!",
    "You’ve got this!",
    "Hard work pays off!",
    "Positivity is a choice!",
    "Small steps lead to big progress!",
    "Believe in your dreams!",
    "Stay humble, work hard!",
    "You can achieve anything!",
    "Make today amazing!",
    "Success starts with effort!",
    "The sky's the limit!",
    "You're capable of greatness!",
    "Keep moving forward!",
    "Your future is bright!",
    "Stay focused on your goals!",
    "Perseverance brings success!",
    "Dream it, achieve it!",
    "Success is a journey!",
    "Stay positive, stay fighting!",
    "Your hard work will pay off!",
    "The best is yet to come!",
    "Believe in yourself!",
    "Every day is a new opportunity!",
    "You’re capable of amazing things!",
    "Keep going, keep growing!",
    "Success is built on hard work!",
    "Your efforts matter!",
    "Never stop learning!",
    "Keep pushing your limits!",
    "Your journey is unique!",
    "Stay consistent and motivated!",
    "You are unstoppable!",
    "Don’t give up now!",
    "Keep challenging yourself!",
    "The only limit is you!",
    "Success comes with effort!",
    "You are stronger than you think!",
    "Every challenge is a step forward!",
    "Stay positive and persistent!",
    "Your dreams are worth it!",
    "Focus on progress, not perfection!",
    "Believe in your potential!",
    "Hard times build strength!",
    "You're writing your success story!",
    "Opportunities are everywhere!",
    "Your mindset shapes your reality!",
    "The key to success is perseverance!",
    "You’re destined for greatness!",
    "Push through your limits!",
    "Small efforts bring big results!",
    "You’re closer than you think!",
    "Consistency is key!",
    "Believe in the power of hard work!",
    "Take pride in how far you’ve come!",
    "You can overcome any obstacle!",
    "Stay focused on your journey!",
    "Your effort is the path to success!",
    "Make every day count!",
    "You are capable of more than you know!",
    "Success is a marathon, not a sprint!",
    "Your determination is your power!",
    "You’re in charge of your future!",
    "Believe, achieve, succeed!",
    "Stay hungry for success!",
    "Take action and make it happen!",
    "Great things are ahead of you!",
    "Every day is a new opportunity to grow!",
    "Keep striving for progress!",
    "You’re unstoppable when you're focused!",
    "Persevere through the challenges!",
    "Your work today shapes your tomorrow!",
    "You’re on the road to success!",
    "Keep working hard, and success will follow!",
    "Your dedication sets you apart!",
    "Success starts with believing in yourself!",
    "Stay resilient and keep pushing!",
    "You’re capable of achieving greatness!",
    "The more you challenge yourself, the more you grow!",
    "Your perseverance is your strength!",
    "You’re destined to accomplish amazing things!"
  ];

  static List<String> getRandomMessages(int count) {
    final random = Random();
    List<String> randomMessages = [];
    for (int i = 0; i < count; i++) {
      randomMessages.add(messages[random.nextInt(messages.length)]);
    }
    return randomMessages;
  }

  static String random() {
    final random = Random();
    return messages[random.nextInt(messages.length)];
  }
}

class RandomNameGenerator {
  static final List<String> firstNames = [
    'Alice',
    'Bob',
    'Charlie',
    'David',
    'Eva',
    'Fiona',
    'George',
    'Hannah',
    'Ivy',
    'Jack',
    'Katherine',
    'Liam',
    'Mia',
    'Noah',
    'Olivia',
    'Parker',
    'Quinn',
    'Ryan',
    'Sophia',
    'Troy',
    'Uma',
    'Violet',
    'William',
    'Xena',
    'Yara',
    'Zoe',
    'Amelia',
    'Benjamin',
    'Catherine',
    'Daniel',
    'Ella',
    'Frank',
    'Grace',
    'Henry',
    'Isabella',
    'James',
    'Kate',
    'Leo',
    'Maya',
    'Nathan',
    'Owen',
    'Paige',
    'Riley',
    'Samuel',
    'Tessa',
    'Ulysses',
    'Victoria',
    'Wyatt',
    'Zach',
    'Aiden',
    'Brooklyn',
    'Chloe',
    'Dylan',
    'Ethan',
    'Freya',
    'Gavin',
    'Hazel',
    'Isaac',
    'Jasmine',
    'Kevin',
    'Luna',
    'Miles',
    'Nora',
    'Oscar',
    'Penelope',
    'Quincy',
    'Ruby',
    'Sebastian',
    'Talia',
    'Uriah',
    'Vera',
    'Walter',
    'Xander',
    'Yasmine',
    'Zara',
  ];

  static final List<String> lastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Jones',
    'Brown',
    'Davis',
    'Miller',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Garcia',
    'Martinez',
    'Robinson',
    'Clark',
    'Rodriguez',
    'Lewis',
    'Lee',
    'Walker',
    'Hall',
    'Allen',
    'Young',
    'Hernandez',
    'King',
    'Wright',
    'Lopez',
    'Hill',
    'Scott',
    'Green',
    'Adams',
    'Baker',
    'Gonzalez',
    'Nelson',
    'Carter',
    'Mitchell',
    'Perez',
    'Roberts',
    'Turner',
    'Phillips',
    'Campbell',
    'Parker',
    'Evans',
    'Edwards',
    'Collins',
    'Stewart',
    'Sanchez',
    'Morris',
    'Rogers',
    'Reed',
    'Cook',
    'Morgan',
    'Bell',
    'Murphy',
    'Cooper',
    'Richardson',
    'Cox',
    'Howard',
    'Ward',
    'Torres',
    'Peterson',
    'Gray',
    'Ramirez',
    'James',
    'Watson',
    'Brooks',
    'Kelly',
    'Sanders',
    'Price',
    'Bennett',
  ];

  static String random() {
    final random = Random();
    final firstName = firstNames[random.nextInt(firstNames.length)];
    final lastName = lastNames[random.nextInt(lastNames.length)];
    return '$firstName $lastName';
  }
}
